### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by sdillenburg** [Till-83/Tibber_Price_Monitor#1]
Hi @Till-83,

I am having trouble compiling the code. Could you please state your versions of the libraries (ESP8266, JSON, Adafruit etc.)?

Thanks
Simon

**Comment by Till-83** [comment]
Sure: 
FQBN: esp8266:esp8266:d1
Using board 'd1' from platform in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2
Using core 'esp8266' from platform in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2

- Using library ArduinoJson at version 6.21.3 in folder: /Users/Till/Documents/Arduino/libraries/ArduinoJson 
- Using library ESP8266HTTPClient at version 1.2 in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/libraries/ESP8266HTTPClient 
- Using library ESP8266WiFi at version 1.0 in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/libraries/ESP8266WiFi 
- Using library Adafruit GFX Library at version 1.11.7 in folder: /Users/Till/Documents/Arduino/libraries/Adafruit_GFX_Library 
- Using library Adafruit BusIO at version 1.14.1 in folder: /Users/Till/Documents/Arduino/libraries/Adafruit_BusIO 
- Using library Wire at version 1.0 in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/libraries/Wire 
- Using library SPI at version 1.0 in folder: /Users/Till/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/libraries/SPI 
- Using library Adafruit NeoMatrix at version 1.3.0 in folder: /Users/Till/Documents/Arduino/libraries/Adafruit_NeoMatrix 
- Using library Adafruit NeoPixel at version 1.11.0 in folder: /Users/Till/Documents/Arduino/libraries/Adafruit_NeoPixel

**Comment by sdillenburg** [comment]
@Till-83 thanks for your reply and sorry for my late response.

My ESP8266 was broken. With another unit, everything worked out of the box.
