### ISSUE TITLE
Leider erhalte ich ständig Fehlermeldungen :/ Haben sie eine Lösung für mich?

### ISSUE THREAD

**Issue by EternalX267** [Till-83/Tibber_Price_Monitor#2]
```
In file included from /Users/Timo/Downloads/Tibber_Price_Monitor-main/Tibber_Price_Monitor/Tibber_Price_Monitor.ino:12:
/Users/Timo/Downloads/Tibber_Price_Monitor-main/Tibber_Price_Monitor/helper_led.h:25:54: error: 'D3' was not declared in this scope
   25 | Adafruit_NeoMatrix matrix = Adafruit_NeoMatrix(8, 8, D3,
      |                                                      ^~

exit status 1

Compilation error: 'D3' was not declared in this scope
```

Was kann ich machen? Ich weiß nicht mehr weiter...

Gruß Timo

**Comment by Till-83** [comment]
D3 ist der Pin, an dem die LED-Matrix angeschlossen ist. 
Falls dies nicht als Konstante deklariert ist, fehlt vermutlich die Library für das verwendete Board, da werden in der Regel die Pins entsprechend definiert und verfügbar gemacht.

**Comment by EternalX267** [comment]
Ich habe das D1 Mini von AZ-Delivery. Ich habe nun statt D3 "0" eingegeben und jetzt funktioniert es! :-)
